## 默认通用的数据源为HikariDataSource，
## 需要修改未其他数据源可以添加 custom.datasource.hive.type=com.alibaba.druid.pool.DruidDataSource
## dataSource or dataSourceClassName or jdbcUrl is required.
##默认数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.52:3306/bloc_xjld_business?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: sendinmuser
    password: sendinmpw
    maximumPoolSize: 20
    connectionTimeout: 30000
    minimumIdle: 2
    idleTimeout: 600000
    connectionTestQuery: select 1
    maxLifetime: 1800000
###更多的数据源
#custom:
#  dataSource:
#    names: business
#    message:
#      dataSourceClassName: com.mysql.jdbc.Driver
#      jdbcUrl: jdbc:mysql://192.168.2.53:3306/bloc_xjld_ybef?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
#      username: sendinmuser
#      password: sendinmpw
#      maximumPoolSize: 20
#      connectionTimeout: 30000
#      minimumIdle: 2
#      idleTimeout: 600000
#      connectionTestQuery: select 1
#      maxLifetime: 1800000
